default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit, manual]
repos:
  - repo: "https://github.com/gitleaks/gitleaks"
    rev: v8.30.0
    hooks:
      - id: gitleaks
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
        exclude: ".tmpl$|^dotfiles/.chezmoitemplates/"
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
        exclude: ".tmpl$|^dotfiles/.chezmoitemplates/"
      - id: check-yaml
        exclude: ".tmpl$|^dotfiles/.chezmoitemplates/"
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
